version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: facepunch
      POSTGRES_DB: ledger
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - 'pg-data:/var/lib/postgresql/data'

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - 'redis-data:/data'


volumes:
  pg-data:
  redis-data:
